### ISSUE TITLE
Note circle doesn't scale properly for mobile

### ISSUE THREAD

**Issue by itsthejoker** [ohnoitsalobo/ohnoitsalobo.github.io#1]
![Screenshot_20220525-083418.png](https://user-images.githubusercontent.com/5179553/170263239-4cab9ab0-c43f-4df9-b4de-615d200a1399.png)

**Comment by ohnoitsalobo** [comment]
Hey man. I honestly I didn't see this until now and I apologize.

As this is sort of a static non-responsive web page, and I'm not really a professional web developer, I wasn't able to make a decent portrait view that would be usable on a small phone screen. You will want to use landscape view on your phone.

I plan at some point to make this into some kind of app or a better-designed webpage; until then, phone portrait view will always be hard to use. Sorry!
